import type { Linter } from "eslint";

export const eslintRules: Linter.RulesRecord = {
	"array-callback-return": "error",
	"constructor-super": "error", // [TS]
	"for-direction": "off", // стандартизированное направление for
	"getter-return": "error", // [TS]
	"no-async-promise-executor": "error",
	"no-await-in-loop": "off", // await внутри циклов
	"no-class-assign": "error", // [TS]
	"no-compare-neg-zero": "error",
	"no-cond-assign": "error",
	"no-const-assign": "error", // [TS]
	"no-constant-binary-expression": ["error", { checkRelationalComparisons: true }],
	"no-constant-condition": "error",
	"no-constructor-return": "error",
	"no-control-regex": "off", // запрещает делать regex с контрол-символами,
	"no-debugger": "error",
	"no-dupe-args": "error", // [TS]
	"no-dupe-class-members": "error", // [TS]
	"no-dupe-else-if": "error",
	"no-dupe-keys": "error", // [TS]
	"no-duplicate-case": "error",
	"no-duplicate-imports": ["error", { allowSeparateTypeImports: true }],
	"no-empty-character-class": "error",
	"no-empty-pattern": "error",
	"no-ex-assign": "error",
	"no-fallthrough": "error",
	"no-func-assign": "error", // [TS]
	"no-import-assign": "error", // [TS]
	"no-inner-declarations": "error", // спорно но можно. Объявление функций внутри { ... }
	"no-invalid-regexp": "error",
	"no-irregular-whitespace": "error",
	"no-loss-of-precision": "error",
	"no-misleading-character-class": "error",
	"no-new-native-nonconstructor": "error", // [TS]
	"no-obj-calls": "error", // [TS]
	"no-promise-executor-return": "error",
	"no-prototype-builtins": "error",
	"no-self-assign": "error",
	"no-self-compare": "error",
	"no-setter-return": "error", // [TS]
	"no-sparse-arrays": "error",
	"no-template-curly-in-string": "error",
	"no-this-before-super": "error", // [TS]
	"no-unassigned-vars": "error",
	"no-undef": "error", // [TS]
	"no-unexpected-multiline": "error",
	"no-unmodified-loop-condition": ["error", { checkConditionalExpressions: true }],
	"no-unreachable": "error", // [TS]
	"no-unreachable-loop": "error",
	"no-unsafe-finally": "error",
	"no-unsafe-negation": "error", // [TS]
	"no-unsafe-optional-chaining": "error",
	"no-unused-private-class-members": "error",
	"no-unused-vars": "error",
	"no-use-before-define": ["error", {
		functions: false,
		classes: false,
		variables: true,
		enums: false,
		typedefs: false,
		ignoreTypeReferences: true,
	}],
	"no-useless-assignment": "error",
	"no-useless-backreference": "error",
	"require-atomic-updates": "off",
	"use-isnan": "error",
	"valid-typeof": "error",

	"no-ternary": "off", // Отключает тернарные операторы
	"no-throw-literal": "error",
	"no-undef-init": "error",
	"no-undefined": "off", // Отключает использование undefined
	"no-underscore-dangle": "off", // Отключает _ в переменных
	"no-unneeded-ternary": "error",
	"no-unused-expressions": "error",
	"no-unused-labels": "error",
	"no-useless-call": "error",
	"no-useless-catch": "error",
	"no-useless-computed-key": "error",
	"no-useless-concat": "error",
	"no-useless-constructor": "error",
	"no-useless-escape": "error",
	"no-useless-rename": "error",
	"no-useless-return": "error",
	"no-var": "error",
	"no-void": ["error", { allowAsStatement: true }],
	"no-warning-comments": "off", // Запрещает писать TODO в комментариях
	"no-with": "error",
	"object-shorthand": "error",
	"one-var": ["error", "never"],
	"operator-assignment": "error",
	"prefer-arrow-callback": "error",
	"prefer-const": "error",
	"prefer-destructuring": ["error", { array: true, object: false }],
	"prefer-exponentiation-operator": "off", // Вместо Math.pow() использовать **. Без разницы
	"prefer-named-capture-group": "warn", // Использовать названия групп в regex. желательно, но не обязательно
	"prefer-numeric-literals": "error",
	"prefer-object-has-own": "error",
	"prefer-object-spread": "error",
	"prefer-promise-reject-errors": "error",
	"prefer-regex-literals": "error",
	"prefer-rest-params": "error",
	"prefer-spread": "error",
	"prefer-template": "error",
	"preserve-caught-error": "off", // Нужно указывать cause в new Error
	"radix": "off",
	"require-await": "error",
	"require-unicode-regexp": "off", // Обязательно указывать /u или /v в regex
	"require-yield": "error",
	"sort-imports": "off", // установлен другой плагин import
	"sort-keys": "off",
	"sort-vars": "error",
	"strict": "off",
	"symbol-description": "error",
	"vars-on-top": "error",
	"yoda": "error",
	"unicode-bom": "error",
	"accessor-pairs": "error", // Спорно, возможно удалится
	"arrow-body-style": "off",
	"block-scoped-var": "error",
	"camelcase": "off", // есть naming-convention с более детальной настройкой
	"capitalized-comments": "off",
	"class-methods-use-this": "off",
	"complexity": "off",
	"consistent-return": "off",
	"consistent-this": "off",
	"curly": ["error", "multi-line"],
	"default-case": "off",
	"default-case-last": "error",
	"default-param-last": "error",
	"dot-notation": "error",
	"eqeqeq": "error",
	"func-name-matching": "error",
	"func-names": "off",
	"func-style": ["error", "declaration", { allowArrowFunctions: true }],
	"grouped-accessor-pairs": "error",
	"guard-for-in": "off",
	"id-denylist": "off",
	"id-length": "off",
	"id-match": "off",
	"init-declarations": "off",
	"logical-assignment-operators": ["error", "always", { enforceForIfStatements: true }],
	"max-classes-per-file": "off",
	"max-depth": "off",
	"max-lines": "off",
	"max-lines-per-function": "off",
	"max-nested-callbacks": ["error", { max: 3, checkConstructorCallCallbacks: true }],
	"max-params": ["error", { max: 6 }],
	"max-statements": "off",
	"new-cap": "off",
	"no-alert": "error",
	"no-array-constructor": "error",
	"no-bitwise": "off",
	"no-caller": "error",
	"no-case-declarations": "error",
	"no-console": "off",
	"no-continue": "off",
	"no-delete-var": "error",
	"no-div-regex": "off",
	"no-else-return": "error",
	"no-empty": ["error", { allowEmptyCatch: true }],
	"no-empty-function": ["error", { allow: ["arrowFunctions"] }],
	"no-empty-static-block": "error",
	"no-eq-null": "error",
	"no-eval": "error",
	"no-extend-native": "error",
	"no-extra-bind": "error",
	"no-extra-boolean-cast": "error",
	"no-extra-label": "error",
	"no-global-assign": "error",
	"no-implicit-coercion": "error",
	"no-implicit-globals": "off",
	"no-implied-eval": "error",
	"no-inline-comments": "off",
	"no-invalid-this": "error", // [TS]
	"no-iterator": "error",
	"no-label-var": "error",
	"no-labels": "error",
	"no-lone-blocks": "error",
	"no-lonely-if": "error",
	"no-loop-func": "off",
	"no-magic-numbers": "off",
	"no-multi-assign": "error",
	"no-multi-str": "error",
	"no-negated-condition": "error",
	"no-nested-ternary": "error",
	"no-new": "off", // new без обозначения. const a = new A(); да, но просто new A() нет
	"no-new-func": "error",
	"no-new-wrappers": "error",
	"no-nonoctal-decimal-escape": "error",
	"no-object-constructor": "error",
	"no-octal": "error",
	"no-octal-escape": "error",
	"no-param-reassign": "error",
	"no-plusplus": "off",
	"no-proto": "error",
	"no-redeclare": "error", // [TS]
	"no-regex-spaces": "error",
	"no-restricted-exports": "off",
	"no-restricted-globals": "off",
	"no-restricted-imports": "off",
	"no-restricted-properties": "off",
	"no-return-assign": "error",
	"no-script-url": "error",
	"no-sequences": "error",
	"no-shadow": "error",
	"no-shadow-restricted-names": "error",
};
