import { Linter } from "eslint";

export const importRules: Linter.RulesRecord = {
	"import/export": "error",
	"import/no-deprecated": "error",
	"import/no-empty-named-blocks": "error",
	"import/no-extraneous-dependencies": "error",
	"import/no-mutable-exports": "error",
	"import/no-named-as-default-member": "error",
	"import/no-unused-modules": "error",
	"import/no-amd": "error",
	"import/no-commonjs": "error",
	"import/no-import-module-exports": "error",
	"import/no-nodejs-modules": "off",
	"import/unambiguous": "error",
	"import/default": "error", // Под вопросом
	"import/enforce-node-protocol-usage": ["error", "always"],
	"import/named": "error", // Под вопросом
	"import/namespace": "error",
	"import/no-absolute-path": "error",
	"import/no-cycle": ["error", {
		maxDepth: 2, // Возможно придется обновить на 1
		ignoreExternal: true,
		allowUnsafeDynamicCyclicDependency: false
	}],
	"import/no-dynamic-require": "error",
	"import/no-internal-modules": "off",
	"import/no-relative-packages": "off",
	"import/no-relative-parent-imports": "off",
	"import/no-self-import": "error",
	"import/no-unresolved": "off",
	"import/no-useless-path-segments": "error",
	"import/no-webpack-loader-syntax": "error",
	"import/consistent-type-specifier-style": ["error", "prefer-top-level"],
	"import/dynamic-import-chunkname": "off",
	"import/exports-last": "off",
	"import/extensions": "off",
	"import/first": "error",
	"import/group-exports": "off",
	"import/max-dependencies": "off",
	"import/newline-after-import": ["error", { count: 1, considerComments: false }],
	"import/no-anonymous-default-export": "error",
	"import/no-default-export": "off",
	"import/no-duplicates": "error",
	"import/no-named-default": "error",
	"import/no-named-export": "off",
	"import/no-namespace": "off",
	"import/no-unassigned-import": "off",
	"import/order": ["error",
		{
			groups: ["builtin", "external", "type", "internal", "parent", "sibling", "index", "object"],
			"newlines-between": "always",
			named: true,
			alphabetize: { order: "asc" },
		},
	],
	"import/prefer-default-export": "off",
};
